services:
  web:
    build: .
    restart: always
    command: >
      sh -c "python manage.py collectstatic --noinput &&
         python manage.py migrate &&
         gunicorn business_tools.wsgi:application --bind 0.0.0.0:8000 --timeout 300 --access-logfile - --error-logfile -"
    volumes:
      - .:/app  # Mount entire project folder
      - ./static:/app/static
      - backups:/backups
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      - db
      - redis

  nginx:
      image: nginx:latest
      restart: always
      ports:
        - "8001:80"
      volumes:
        - ./nginx:/etc/nginx/conf.d:ro  
        - ./static:/app/static:ro  # Ο Nginx διαβάζει τα static (Read-Only)
      depends_on:
        - web


  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  backups:
  static_volume: