# Generated by Django 6.0.3 on 2026-06-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='products',
            name='unit',
            field=models.CharField(default='τμχ', max_length=20),
            preserve_default=False,
        ),
    ]
