# Generated by Django 6.0.3 on 2026-06-15 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenses', '0012_alter_fixedexpenses_amount_and_more'),
        ('invoices', '0002_invoice_paid_products_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AddField(
            model_name='invoice',
            name='expense',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='income_expenses.expenses'),
        ),
    ]
