# Generated by Django 6.0.3 on 2026-07-11 20:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenses', '0016_remove_income_predicted_income_incomeprediction'),
        ('invoices', '0003_alter_products_options_invoice_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='afm',
        ),
        migrations.AddField(
            model_name='invoice',
            name='fpa_persentage',
            field=models.IntegerField(default=24, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afm', models.CharField(db_index=True, max_length=9, unique=True)),
                ('supplier', models.CharField(max_length=200)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income_expenses.store')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='new_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='invoices.supplier'),
        ),
    ]
