# Generated by Django 6.0.3 on 2026-07-12 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_invoice_afm_invoice_fpa_persentage_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='new_supplier',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoices.supplier'),
        ),
    ]
