# Generated by Django 6.0.3 on 2026-07-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_invoice_new_supplier_alter_invoice_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='store',
        ),
    ]
