# Generated by Django 6.0.3 on 2026-03-07 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenses', '0002_alter_expenses_category_alter_income_income_cash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name': 'expense', 'verbose_name_plural': 'expenses'},
        ),
        migrations.AddField(
            model_name='expenses',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='income_expenses.store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='income',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='income_expenses.store'),
            preserve_default=False,
        ),
    ]
