# Generated by Django 6.0.3 on 2026-03-07 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenses', '0003_store_alter_expenses_options_expenses_store_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='income_expenses.store'),
        ),
    ]
