# Generated by Django 6.0.3 on 2026-03-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenses', '0004_alter_income_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
