# Generated by Django 6.0.3 on 2026-03-21 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenses', '0006_store_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='day',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='income',
            unique_together={('store', 'day')},
        ),
    ]
