# Generated by Django 6.0.3 on 2026-05-09 04:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenses', '0007_alter_income_day_alter_income_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
        name='store',
        unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='store',
            name='user',
        ),
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('name', 'user')},
        ),
    ]
