# Generated by Django 6.0.3 on 2026-05-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenses', '0009_fixedexpenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedexpenses',
            name='next_charge_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
