# Generated by Django 6.0.3 on 2026-05-31 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenses', '0010_alter_fixedexpenses_next_charge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='predicted_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
