# Generated by Django 6.0.3 on 2026-05-31 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenses', '0011_income_predicted_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedexpenses',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσό'),
        ),
        migrations.AlterField(
            model_name='fixedexpenses',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Καθημερινή'), ('WEEKLY', 'Εβδομαδιαία'), ('MONTHLY', 'Μηνιαία'), ('ANNUAL', 'Ετήσια')], default='MONTHLY', verbose_name='Συχνότητα'),
        ),
        migrations.AlterField(
            model_name='fixedexpenses',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Όνομα'),
        ),
        migrations.AlterField(
            model_name='fixedexpenses',
            name='start_date',
            field=models.DateField(verbose_name='Ημερομηνία εκκίνησης'),
        ),
        migrations.AlterField(
            model_name='fixedexpenses',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income_expenses.store', verbose_name='Κατάστημα'),
        ),
    ]
