# Generated by Django 6.0.3 on 2026-06-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenses', '0012_alter_fixedexpenses_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedexpenses',
            name='category',
            field=models.CharField(blank=True, choices=[('WITH_FPA_TAX', 'ΜΕ ΦΠΑ 24%'), ('WITHOUT_FPA_TAX', 'ΧΩΡΙΣ ΦΠΑ')], max_length=100),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(blank=True, choices=[('WITH_FPA_TAX', 'ΜΕ ΦΠΑ 24%'), ('WITHOUT_FPA_TAX', 'ΧΩΡΙΣ ΦΠΑ')], max_length=100),
        ),
    ]
