# Generated by Django 6.0.3 on 2026-06-23 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenses', '0014_aiusagelimit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AI_Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.IntegerField(default=10)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income_expenses.store')),
            ],
        ),
        migrations.CreateModel(
            name='AI_Usage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income_expenses.store')),
            ],
        ),
        migrations.DeleteModel(
            name='AIUsageLimit',
        ),
    ]
