# Generated by Django 6.0.3 on 2026-06-25 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenses', '0015_ai_limit_ai_usage_delete_aiusagelimit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='predicted_income',
        ),
        migrations.CreateModel(
            name='IncomePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('predicted_income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='income_expenses.store')),
            ],
            options={
                'unique_together': {('store', 'day')},
            },
        ),
    ]
