# Generated by Django 6.0.3 on 2026-07-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income_expenses', '0016_remove_income_predicted_income_incomeprediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='category',
            field=models.CharField(blank=True, choices=[('WITH_FPA_6', 'ΜΕ ΦΠΑ 6%'), ('WITH_FPA_13', 'ΜΕ ΦΠΑ 13%'), ('WITH_FPA_TAX', 'ΜΕ ΦΠΑ 24%'), ('WITHOUT_FPA_TAX', 'ΧΩΡΙΣ ΦΠΑ')], max_length=100),
        ),
    ]
