# server {
#     listen 80;
#     client_max_body_size 10M;


#     location /static/ {
#         alias /app/static/;
#         expires max;
#         access_log off;
#     }

#     location / {
#         proxy_pass http://web:8000;
#         proxy_set_header Host $host;
#         proxy_set_header X-Real-IP $remote_addr;
#         proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#         proxy_set_header X-Forwarded-Proto $scheme;
        
#         proxy_connect_timeout 60s;
#         proxy_read_timeout 60s;
#         proxy_send_timeout 60s;
#     }
# }

server {
    listen 80;
    client_max_body_size 10M;

    location /static/income_expenses/ {
        alias /app/income_expenses/static/income_expenses/;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
    location /static/invoices/ {
        alias /app/invoices/static/invoices/;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }
    location /static/ai_assistant/ {
        alias /app/ai_assistant/static/ai_assistant/;
        add_header Cache-Control "no-cache, no-store, must-revalidate";
    }

    location /static/ {
        alias /app/static/;
        expires max;
        access_log off;
    }

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        proxy_connect_timeout 60s;
        proxy_read_timeout 60s;
        proxy_send_timeout 60s;
    }
}